#ifndef VERSION_UTILS_H_IN
#define VERSION_UTILS_H_IN

#define EYS3D_DEPTH_VERSION_MAJOR 1
#define EYS3D_DEPTH_VERSION_MINOR 0
#define EYS3D_DEPTH_VERSION_PATCH 0
#define EYS3D_DEPTH_VERSION_TWEAK 1

#define WRAPPER_VERSION "1.0.0.1"
#define GIT_BRANCH "sinet_dev"
#define GIT_HASH "24553e3"
#define BUILD_TIMESTAMP "2022-09-13 06:36:07"

#endif // VERSION_UTILS_H_IN
