# https://github.com/softprops/action-gh-release
name: draft-release

on:
  push:
    tags:
      - 'v*'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get custom tarball name
        id: get_tarball_name
        run: |
          echo "TARBALL_NAME=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Shell PWD
        run: |
          pwd
          ls -al

      - name: Create custom tarball artifact
        run: |
          cd ../
          mkdir -p artifacts
          tar czvf artifacts/${{ steps.get_tarball_name.outputs.TARBALL_NAME }}.tar.gz --exclude-vcs ./${{ github.event.repository.name }}
          
      - name: Create release and upload asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ../artifacts/${{ steps.get_tarball_name.outputs.TARBALL_NAME }}.tar.gz
